name: sol-github-actions
on: [push]
jobs:
  checkout-compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g solc
      - run: sudo add-apt-repository ppa:ethereum/ethereum
      - run: sudo apt-get update
      - run: sudo apt-get install solc
      - run: solc -o outputDirectory --bin --ast-json --asm *.sol
